name: Gold Rate Scraper

on:
  schedule:
    # IST = UTC + 5:30
    # 09:47 AM IST = 04:17 UTC
    - cron: '17 4 * * *'

    # 12:41 PM IST = 07:11 UTC
    - cron: '11 7 * * *'

    # 02:53 PM IST = 09:23 UTC
    - cron: '23 9 * * *'
    
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python scraper.py
